using Microsoft.EntityFrameworkCore;
using PdfSharp.Drawing;
using PdfSharp.Pdf;
using VidFlow.Api.Data;

namespace VidFlow.Api.Features.Export;

public static class ExportStoryboardPdf
{
    public static void MapEndpoint(IEndpointRouteBuilder app)
    {
        app.MapGet("/api/projects/{projectId}/export/storyboard.pdf", Handler)
           .WithName("ExportStoryboardPdf")
           .WithTags("Export")
           .Produces(StatusCodes.Status200OK, contentType: "application/pdf");
    }

    private static async Task<IResult> Handler(
        Guid projectId,
        VidFlowDbContext db,
        CancellationToken ct)
    {
        var project = await db.Projects
            .Include(p => p.Scenes)
            .FirstOrDefaultAsync(p => p.Id == projectId, ct);

        if (project is null)
            return Results.NotFound($"Project {projectId} not found");

        var scenes = await db.Scenes
            .Where(s => s.ProjectId == projectId)
            .Include(s => s.Shots)
            .OrderBy(s => s.Number)
            .ToListAsync(ct);

        var assets = await db.Assets
            .Where(a => a.ProjectId == projectId)
            .ToListAsync(ct);

        var document = new PdfDocument();
        document.Info.Title = $"Storyboard - {project.Title}";

        var page = document.AddPage();
        var gfx = XGraphics.FromPdfPage(page);

        var fontTitle = new XFont("Helvetica", 18, XFontStyleEx.Bold);
        var fontHeader = new XFont("Helvetica", 12, XFontStyleEx.Bold);
        var fontBody = new XFont("Helvetica", 10, XFontStyleEx.Regular);
        var fontSmall = new XFont("Helvetica", 9, XFontStyleEx.Regular);

        double margin = 40;
        double y = margin;
        double lineHeight = 14;
        double pageHeight = page.Height.Point;
        double pageWidth = page.Width.Point;

        void NewPage()
        {
            page = document.AddPage();
            gfx.Dispose();
            gfx = XGraphics.FromPdfPage(page);
            pageHeight = page.Height.Point;
            pageWidth = page.Width.Point;
            y = margin;
        }

        void DrawLine(string text, XFont font)
        {
            if (y + lineHeight > pageHeight - margin)
                NewPage();

            gfx.DrawString(text, font, XBrushes.Black, new XRect(margin, y, pageWidth - margin * 2, lineHeight), XStringFormats.TopLeft);
            y += lineHeight;
        }

        // Title
        DrawLine($"Storyboard - {project.Title}", fontTitle);
        y += 6;

        foreach (var scene in scenes)
        {
            DrawLine($"Scene {scene.Number}: {scene.Title}", fontHeader);
            DrawLine($"Location: {scene.Location} | Time: {scene.TimeOfDay}", fontSmall);
            DrawLine($"Narrative Goal: {scene.NarrativeGoal}", fontSmall);
            DrawLine($"Emotional Beat: {scene.EmotionalBeat}", fontSmall);

            if (!scene.Shots.Any())
            {
                DrawLine("(No shots)", fontBody);
                y += 6;
                continue;
            }

            foreach (var shot in scene.Shots.OrderBy(s => s.Number))
            {
                DrawLine($"  Shot {shot.Number}: {shot.Type} ({shot.Duration})", fontBody);

                if (!string.IsNullOrWhiteSpace(shot.Description))
                    DrawLine($"    {shot.Description}", fontSmall);

                if (!string.IsNullOrWhiteSpace(shot.Camera))
                    DrawLine($"    Camera: {shot.Camera}", fontSmall);

                var shotAssets = assets
                    .Where(a => a.SceneId == scene.Id && a.ShotId == shot.Id)
                    .OrderByDescending(a => a.CreatedAt)
                    .ToList();

                if (shotAssets.Any())
                {
                    foreach (var a in shotAssets)
                    {
                        DrawLine($"    Asset [{a.Type}/{a.Status}] - {a.Name}", fontSmall);
                        if (!string.IsNullOrWhiteSpace(a.Url))
                            DrawLine($"      {a.Url}", fontSmall);
                    }
                }
                else
                {
                    DrawLine("    (No assets)", fontSmall);
                }

                y += 4;
            }

            y += 10;
        }

        // Footer on last page only (simple)
        if (y + lineHeight > pageHeight - margin)
            NewPage();
        gfx.DrawString($"Generated by VidFlow Studio | {DateTime.UtcNow:yyyy-MM-dd HH:mm}", fontSmall, XBrushes.Gray,
            new XRect(margin, pageHeight - margin + 10, pageWidth - margin * 2, lineHeight), XStringFormats.TopLeft);

        using var ms = new MemoryStream();
        document.Save(ms);
        return Results.File(ms.ToArray(), "application/pdf", fileDownloadName: $"storyboard_{projectId}.pdf");
    }
}
